### ISSUE TITLE
when i try to run, i get ImportError: dlopen error

### ISSUE THREAD

**Issue by kelvinblade** [BoBeR182/Pokemon-Go-Bot-Working-Hack-API#19]
Here's the full error:

Traceback (most recent call last):
  File "pokebot.py", line 15, in <module>
    from pgoapi import PGoApi
  File "/Users/kel/Documents/code/test/poke1/pgoapi/__init__.py", line 3, in <module>
    import pkg_resources
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 21, in <module>
    import io
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/io.py", line 51, in <module>
    import _io
ImportError: dlopen(/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so, 2): Symbol not found: __PyCodecInfo_GetIncrementalDecoder
  Referenced from: /usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so
  Expected in: flat namespace
 in /usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so

How can I fix it? Thanks

**Comment by BoBeR182** [comment]
Do you have pip installed and all the dependencies, what OS version?

**Comment by kelvinblade** [comment]
osx 10.11.5

i am new to python. i did brew install python. i think that installed pip.

then i ran pip install urllib3 --upgrade because there was an urllib3 error.

then i ran pip install -r requirement.txt

then python pokebot.py -i 0 --cache and got this error.

Am I missing other dependencies? What command should I use? Thanks!

**Comment by BoBeR182** [comment]
I do not run OS X, try `sudo pip install -r requirements.txt` if that fails, maybe someone else got it running, or Linux virtual machines are an option.
