### ISSUE TITLE
Main loop has an error when evaluating pokeball number

### ISSUE THREAD

**Issue by JohnQUnknown** [BoBeR182/Pokemon-Go-Bot-Working-Hack-API#20]
I ran this bot on a new account that I created for testing, after I went through the tutorial in my phone I set it up in the bot and ran it, everything seems to be ok until it's time to evaluate whether or not we need more pokeballs, I had set the minimum value to 5 before and it seems like the bot discarded the rest of my pokeballs (I had 15), but now it seems like it always tries to farm pokestops because it's determining that I need more Pokeballs, after that it fails with the following error message:

`2016-07-28 02:04:25,437 [   pokebot] [ERROR] Main loop has an ERROR, restarting list index out of range
Traceback (most recent call last):
  File "pokebot.py", line 95, in main
    api.main_loop()
  File "/home/user/projects/Pokemon-Go-Bot-Working-Hack-API/pgoapi/pgoapi.py", line 489, in main_loop
    if self.pokeballs[self._pokeball_type] > 1: # make sure we always have at least 10 pokeballs, 5 great balls, and 5 ultra balls
IndexError: list index out of range
^CTraceback (most recent call last):
  File "pokebot.py", line 105, in <module>
    main()
  File "pokebot.py", line 99, in main
    main()
  File "pokebot.py", line 98, in main
    sleep(30)
KeyboardInterrupt`

**Comment by BoBeR182** [comment]
What commit are you running? OS version? and post config.json without any personal details.

**Comment by JohnQUnknown** [comment]
Hi, 

I'm running on Ubuntu 14.04 and on the master branch, my config.json is as follows:


`{"accounts" :
    [{
        "auth_service": "google",
        "username": "test@gmail.com",
        "password": "password",
        "location": "Irvine, CA",
        "USE_GOOGLE": true,
        "GMAPS_API_KEY": ["API-KEY"],
        "MIN_KEEP_IV" : 50,
        "KEEP_CP_OVER": 500,
        "RELEASE_DUPLICATE": true,
        "DUPLICATE_CP_FOREGIVENESS": 0.90,
        "STEP_SIZE": 20,
        "RETURN_START_INTERVAL": 20,
        "MAX_BALL_TYPE": 2,
        "MIN_ITEM_COUNTS": {
            "ITEM_POKE_BALL": 15,
            "ITEM_GREAT_BALL": 25,
            "ITEM_ULTRA_BALL": 95,
            "ITEM_POTION": 5,
            "ITEM_SUPER_POTION": 5,
            "ITEM_HYPER_POTION": 30,
            "ITEM_MAX_POTION": 60,
            "ITEM_RAZZ_BERRY": 20,
            "ITEM_BLUK_BERRY": 10,
            "ITEM_NANAB_BERRY": 10,
            "ITEM_REVIVE": 25
        }
    },
    {  "auth_service": "ptc",
        "username": "MyUser",
        "password": "MyPassword",
        "location": "40.7828687,-73.9675438",
        "USE_GOOGLE": true,
        "GMAPS_API_KEY": ["MyAPIKey"],
        "MIN_KEEP_IV" : 50,
        "KEEP_CP_OVER": 200,
        "RELEASE_DUPLICATE": true,
        "DUPLICATE_CP_FOREGIVENESS": 0.90,
        "STEP_SIZE": 100,
        "RETURN_START_INTERVAL": 20,
        "MAX_BALL_TYPE": 2,
        "MIN_ITEM_COUNTS": {
            "ITEM_POKE_BALL": 5,
            "ITEM_GREAT_BALL": 15,
            "ITEM_ULTRA_BALL": 95,
            "ITEM_POTION": 5,
            "ITEM_SUPER_POTION": 5,
            "ITEM_HYPER_POTION": 30,
            "ITEM_MAX_POTION": 60,
            "ITEM_RAZZ_BERRY": 20,
            "ITEM_BLUK_BERRY": 10,
            "ITEM_NANAB_BERRY": 10,
            "ITEM_REVIVE": 25
        }
    }
    ]}
`

**Comment by BoBeR182** [comment]
Try updating to the latest commit you might be running the bot before that bug was fixed in 48cb00eac4a3042536658162abd7f87f3bbcd8f3

**Comment by BRZ420** [comment]
I have this crash on latest master, if there are no regular pokeballs left

```
2016-08-02 18:18:30,195 [   pokebot] [ERROR] Main loop has an ERROR, restarting 'NoneType' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "pokebot.py", line 100, in main
    api.main_loop()
  File "/work/pokemon/bot-new/pgoapi/pgoapi.py", line 601, in main_loop
    self.spin_near_fort()  # check local pokestop
  File "/work/pokemon/bot-new/pgoapi/pgoapi.py", line 286, in spin_near_fort
    self.walk_to((fort['latitude'], fort['longitude']))
  File "/work/pokemon/bot-new/pgoapi/pgoapi.py", line 246, in walk_to
    while self.catch_near_pokemon():
  File "/work/pokemon/bot-new/pgoapi/pgoapi.py", line 318, in catch_near_pokemon
    return self.encounter_pokemon(target[0])
  File "/work/pokemon/bot-new/pgoapi/pgoapi.py", line 492, in encounter_pokemon
    capture_status = catch_attempt['status']
TypeError: 'NoneType' object has no attribute '__getitem__'

```
